nodeLinker: node-modules

npmScopes:
  sesamecare:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://us-central1-npm.pkg.dev/sesame-care-dev/npm-packages/"
    npmRegistryServer: "https://us-central1-npm.pkg.dev/sesame-care-dev/npm-packages/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-gcp-auth.cjs
    spec: "https://github.com/AndyClausen/yarn-plugin-gcp-auth/releases/latest/download/plugin-gcp-auth.js"

yarnPath: .yarn/releases/yarn-3.8.7.cjs
